### ISSUE TITLE
npmjs availability

### ISSUE THREAD

**Issue by rjjrbatarao** [Sirherobrine23/node-tap#5]
Hello thank you for your work on this, I want to try this but cannot find on npmjs the actual package. do you have a link how to do npm I on this??

**Comment by Sirherobrine23** [comment]
hi, this package not maintained and npm nothing found another packages to create network tap, current this package not working

**Comment by Sirherobrine23** [comment]
i create this package to make tap with node addon, maintenance i very hard and nothings work because my implementation and bad code

**Comment by Sirherobrine23** [comment]
@rjjrbatarao I wanted to make this package work, because I wanted a connection per streamer, but I was asked for implementation, because the main platforms would be Windows, Linux and Android. But it ended up being sendable, the development of the package continues because each system would have to have a totally different implementation, and Android would make it more unfeasible possible.

**Comment by Sirherobrine23** [comment]
many's repository migrating to my git server https://sirherobrine23.org and current making maintence to `wireguard-tools.js` and another projects
